### PR TITLE
Update location and scripts

### PR DESCRIPTION
**Pull request by BrianHGrant**
This pr is to update to current working versions of the deploy scripts, and update the project organization to match updated cookiecutter

### CODE REVIEW

**Review by DingoEatingFuzz — APPROVED** [review]
Looks good!

My two idle thoughts at the moment that are bigger than this PR are

1. We're hardcoding paths for scripts but those paths are actually dependent on where we copy things into the container. I wonder if there is a good way to make that less brittle.

2. I appreciate the renaming of `bin/*.sh` to `/scripts/deploy/*.sh` to match where files get mapped, but I would like for this repo to grow into a single source for scripts of all deploy types, including frontend and maybe different APIs.

**Comment by nam20485** [comment]
@DingoEatingFuzz 

>I appreciate the renaming of bin/*.sh to /scripts/deploy/*.sh to match where files get mapped, but I would like for this repo to grow into a single source for scripts of all deploy types, including frontend and maybe different APIs.

OK- so you would like to go one step further and add another level like thusly?:

```
scripts/
   deploy/
       front-end/
       backend-apiX/     
       backend-apiY/
```

**Review by nam20485 — APPROVED** [review]
Lgtm

**Comment by DingoEatingFuzz** [comment]
> OK- so you would like to go one step further and add another level like thusly?

I'm not too concerned about the precise format, but I was imagining `type` being the root directory:

```
front-end/
backend-apiX/
    scripts/
      deploy/
backend-apiY
    bin/
      who-knows/
```

I think this allows for the most flexibility per project, but I can easily be convinced of something else.

**Comment by nam20485** [comment]
I need one of the changes in here so I merged it. I'll create an additional PR to address the last concern. I think `type` as the top-level makes sense.

**Pull request merged**
